### ISSUE TITLE
Port to english and maybe persian language

### ISSUE THREAD

**Issue by mbaneshi** [xssnick/ton-deep-doc#3]
Hey, @xssnick.Thank you for this valuable resource. If there is no problem I am eager to translate it from Russia, I want to know your thoughts, and where is the suitable place to put the result.
Also, I will be happy to know, in case of any consideration.

**Comment by xssnick** [comment]
Hi, I think translation to different languages is always good. Just want to let you know that english translation is already available in ton docs as a different articles, example: https://docs.ton.org/develop/network/adnl-udp (it is also enhanced there with some additional info)

The best place will be ton docs, because there it can reach more people, but not sure about diff languages support there. Maybe you could reach someone at https://github.com/ton-community/ton-docs/tree/main to discuss
